version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "yearly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/macos"
      - "/.github/actions/windows"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
