name: windows
inputs:
  py_version:
    required: true
runs:
  using: composite
  steps:
  - uses: conda-incubator/setup-miniconda@be893c923ea9cf1cf7cd510fbdde27c7e18cbdcb # v4.1.0
    with:
      miniconda-version: "latest"
      python-version: ${{ inputs.py_version }}
      activate-environment: hydra
  - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
    with:
      distribution: 'microsoft'
      java-version: '21'
