# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Start fish without user configuration
set env(HOME) [exec mktemp -d]
puts "HOME: $env(HOME)"

set in_line [lindex $argv 1]
set len [expr [string length $in_line] - 1]
set line [string range $in_line 5 $len]
puts "input line: '$line'"

set command "[lindex $argv 0] $line"
puts "command: '$command'"

set fish_script "[lindex $argv 0] -sc install=fish | source; complete --do-complete \"$command\""
if {[catch {exec fish -c $fish_script} completions]} {
    puts "Error running fish completion: '$completions'"
    exit 2
}

puts "\nMatching:\n"
foreach arg [lrange $argv 3 end] {
    if {[string first $arg $completions] < 0} {
        puts "Error matching $arg\noutput: '$completions'"
        exit 1
    }
    puts "matched '$arg' to completion output"
}
